#!/bin/bash

set -e

user="$1"
token="$2"
version="$3"

export GIT_AUTHOR_NAME="BabelBot"
export GIT_AUTHOR_EMAIL="bot@babeljs.io"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"

git init
git fetch https://github.com/babel/ruby-babel-transpiler

null_blob="e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"

parent=$(git rev-parse FETCH_HEAD)
subdir="source-versions"
old_source=$(git ls-tree -l "$parent" "$subdir" | cut -d' ' -f3)

entry="100644 blob $null_blob	$version"
new_source=$((git ls-tree "$old_source"; echo "$entry") | git mktree)
tree=$(git ls-tree "$parent" | sed "s/$old_source/$new_source/g" | git mktree)

message="Release $version"
commit=$(echo "$message" | git commit-tree "$tree" -p "$parent")

ref="refs/heads/release-$version"
git update-ref "$ref" "$commit"
git push "https://$token@github.com/$user/ruby-babel-transpiler.git" "$ref"
git update-ref -d "$ref"

url="https://api.github.com/repos/babel/ruby-babel-transpiler/pulls"
body="{\"title\": \"Release $version\", \"base\": \"master\", \"head\": \"$user:release-$version\"}"
header="Authorization: token $token"
echo "$body" | curl -H "$header" -X POST -d @- "$url"
