#!/bin/bash

set -e
set -x

VERSION="$1"
GEM_VERSION=$(./script/gem-version $VERSION)

mkdir -p tmp/
pushd tmp/

if [ ! -d babel ]; then
  git clone https://github.com/babel/babel
fi

pushd babel/
git fetch origin

git checkout --quiet "v$VERSION"
make bootstrap build-dist
popd

BROWSERIFY_CMD="../babel/node_modules/browserify/bin/cmd.js"

mkdir -p babel-core/{node_modules,dist}
pushd babel-core
ln -s ../../babel/packages/babel-core node_modules/babel-core
cat <<JS | node $BROWSERIFY_CMD --insert-global-vars global --outfile dist/babel-core.js -
global.babel = require('babel-core');
JS
popd

mkdir -p babel-cli/{node_modules,dist}
pushd babel-cli
ln -s ../../babel/packages/babel-cli node_modules/babel-cli
cat <<JS | node $BROWSERIFY_CMD --insert-global-vars global --outfile dist/external-helpers.js -
global.babelHelpers = require('babel-cli/lib/babel-external-helpers');
JS
popd

popd

DATE=$(git show --format=%at | head -n1)

dir="tmp/babel-source-$VERSION"
mkdir -p "$dir/lib/babel"
cp "tmp/babel-core/dist/babel-core.js" "$dir/lib/babel.js"
cp "tmp/babel-cli/dist/external-helpers.js" "$dir/lib/babel/external-helpers.js" # 
cp "tmp/babel/packages/babel-polyfill/dist/polyfill.js" "$dir/lib/babel/polyfill.js"

cp "tmp/babel/LICENSE" "$dir/LICENSE"
./script/eval-erb-template "babel-source.gemspec.erb" "$GEM_VERSION" "$DATE" > "$dir/babel-source.gemspec"
./script/eval-erb-template "lib/babel/source.rb.erb" "$GEM_VERSION" "$DATE" > "$dir/lib/babel/source.rb"

pushd "$dir"
gem build babel-source.gemspec
popd

mkdir -p tmp/vendor/cache
cp "$dir/babel-source-$GEM_VERSION.gem" "tmp/vendor/cache"
