#!/bin/bash

set -e
set -x

VERSION="$1"
GEM_VERSION=$(./script/gem-version $VERSION)

mkdir -p tmp/
pushd tmp/

if [ ! -d babel ]; then
  git clone https://github.com/babel/babel
fi

pushd babel/
git fetch origin

git checkout --quiet "v$VERSION"
make bootstrap build-dist

DATE=$(git show --format=%at | head -n1)

popd
popd

dir="tmp/babel-source-$VERSION"
mkdir -p "$dir/lib/babel"
cp "tmp/babel/packages/babel/dist/browser.js" "$dir/lib/babel.js"
cp "tmp/babel/packages/babel/dist/external-helpers.js" "$dir/lib/babel/external-helpers.js"
cp "tmp/babel/packages/babel/dist/polyfill.js" "$dir/lib/babel/polyfill.js"

cp "tmp/babel/LICENSE" "$dir/LICENSE"
./script/eval-erb-template "babel-source.gemspec.erb" "$GEM_VERSION" "$DATE" > "$dir/babel-source.gemspec"
./script/eval-erb-template "lib/babel/source.rb.erb" "$GEM_VERSION" "$DATE" > "$dir/lib/babel/source.rb"

pushd "$dir"
gem build babel-source.gemspec
popd

mkdir -p tmp/vendor/cache
cp "$dir/babel-source-$GEM_VERSION.gem" "tmp/vendor/cache"
