#!/bin/bash

set -e

if [ -n "$TRAVIS" ] && ([ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || [ "$TRAVIS_BRANCH" != "master" ] || [ -z "$BUILD_SOURCE_GEM" ])
then
  exit 0
fi

if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
  cat << EOF > ~/.gem/credentials
---
:rubygems_api_key: $RUBYGEMS_API_KEY
EOF
  chmod 0600 ~/.gem/credentials
fi

for version in $(./script/unpublished-source-versions)
do
  ./script/publish-gem "$version"
done
